### ISSUE TITLE
Users are not displayed

### ISSUE THREAD

**Issue by YTEntity303** [OfficialAhmed/MyTrophies-PS4#4]
When I connect to the ps4 and click on "Fetch users" the users do not appear

**Comment by OfficialAhmed** [comment]
- does it show an error when fetch users clicked? 
- does "CONNECTED" displayed before you tried to fetch?

**Comment by YTEntity303** [comment]
> * does it show an error when fetch users clicked?
> * does "CONNECTED" displayed before you tried to fetch?

When I click connect, it connects smoothly, but when I click on fetch nothing happens

**Comment by OfficialAhmed** [comment]
I haven't tried it on a jailbroken PS4, that's why it's an alpha version. I'll look into it thank you

**Comment by OfficialAhmed** [comment]
I've found the issue and working on an update, keep an eye on the releases.

**Comment by YTEntity303** [comment]
> I've found the issue and working on an update, keep an eye on the releases.

Thank you
